name: solana_trader
author: valory
version: 0.1.0
description: A set of agents trading tokens
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiasyvanypleay7yspri6igebqccpm3a7uvvrlna5yjkzdsnvcbu4q
fingerprint_ignore_patterns: []
agent: valory/solana_trader:0.1.0:bafybeiejyucgf3qygy6nyjqvzil44atugdfrq7qqxau76w2bcwduktweee
number_of_agents: 4
deployment: {}
---
public_id: valory/ipfs_package_downloader:0.1.0
type: skill
0:
  models:
    params:
      args:
        cleanup_freq: ${CLEANUP_FREQ:int:50}
        timeout_limit: ${TIMEOUT_LIMIT:int:3}
        file_hash_to_id: ${FILE_HASH_TO_ID:list:[["bafybeifkgo6wmjjku4h65sdqnaby7tczp3cropted5vtdxryevawdqnb4i",["sma_strategy"]]]}
        component_yaml_filename: ${COMPONENT_YAML_FILENAME:str:component.yaml}
        entry_point_key: ${ENTRY_POINT_KEY:str:entry_point}
        run_callable_key: ${RUN_CALLABLE_KEY:str:run_callable}
        transform_callable_key: ${TRANSFORM_CALLABLE_KEY:str:transform_callable}
        evaluate_callable_key: ${EVALUATE_CALLABLE_KEY:str:evaluate_callable}
1:
  models:
    params:
      args:
        cleanup_freq: ${CLEANUP_FREQ:int:50}
        timeout_limit: ${TIMEOUT_LIMIT:int:3}
        file_hash_to_id: ${FILE_HASH_TO_ID:list:[["bafybeifkgo6wmjjku4h65sdqnaby7tczp3cropted5vtdxryevawdqnb4i",["sma_strategy"]]]}
        component_yaml_filename: ${COMPONENT_YAML_FILENAME:str:component.yaml}
        entry_point_key: ${ENTRY_POINT_KEY:str:entry_point}
        run_callable_key: ${RUN_CALLABLE_KEY:str:run_callable}
        transform_callable_key: ${TRANSFORM_CALLABLE_KEY:str:transform_callable}
        evaluate_callable_key: ${EVALUATE_CALLABLE_KEY:str:evaluate_callable}
2:
  models:
    params:
      args:
        cleanup_freq: ${CLEANUP_FREQ:int:50}
        timeout_limit: ${TIMEOUT_LIMIT:int:3}
        file_hash_to_id: ${FILE_HASH_TO_ID:list:[["bafybeifkgo6wmjjku4h65sdqnaby7tczp3cropted5vtdxryevawdqnb4i",["sma_strategy"]]]}
        component_yaml_filename: ${COMPONENT_YAML_FILENAME:str:component.yaml}
        entry_point_key: ${ENTRY_POINT_KEY:str:entry_point}
        run_callable_key: ${RUN_CALLABLE_KEY:str:run_callable}
        transform_callable_key: ${TRANSFORM_CALLABLE_KEY:str:transform_callable}
        evaluate_callable_key: ${EVALUATE_CALLABLE_KEY:str:evaluate_callable}
3:
  models:
    params:
      args:
        cleanup_freq: ${CLEANUP_FREQ:int:50}
        timeout_limit: ${TIMEOUT_LIMIT:int:3}
        file_hash_to_id: ${FILE_HASH_TO_ID:list:[["bafybeifkgo6wmjjku4h65sdqnaby7tczp3cropted5vtdxryevawdqnb4i",["sma_strategy"]]]}
        component_yaml_filename: ${COMPONENT_YAML_FILENAME:str:component.yaml}
        entry_point_key: ${ENTRY_POINT_KEY:str:entry_point}
        run_callable_key: ${RUN_CALLABLE_KEY:str:run_callable}
        transform_callable_key: ${TRANSFORM_CALLABLE_KEY:str:transform_callable}
        evaluate_callable_key: ${EVALUATE_CALLABLE_KEY:str:evaluate_callable}
---
public_id: valory/solana_trader_abci:0.1.0
type: skill
0:
  models:
    params:
      args:
        setup: &id002
          all_participants: ${ALL_PARTICIPANTS:list:[]}
          safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:unknown111111111111111111111111111111111111}
          consensus_threshold: ${CONSENSUS_THRESHOLD:int:null}
        cleanup_history_depth: ${CLEANUP_HISTORY_DEPTH:int:1}
        cleanup_history_depth_current: ${CLEANUP_HISTORY_DEPTH_CURRENT:int:null}
        drand_public_key: ${DRAND_PUBLIC_KEY:str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
        finalize_timeout: ${FINALIZE_TIMEOUT:float:60.0}
        genesis_config: &id003
          genesis_time: ${GENESIS_TIME:str:'2023-07-12T00:00:00.000000000Z'}
          chain_id: ${GENESIS_CHAIN_ID:str:chain-c4daS1}
          consensus_params:
            block:
              max_bytes: ${BLOCK_MAX_BYTES:str:'22020096'}
              max_gas: ${MAX_GAS:str:'-1'}
              time_iota_ms: ${TIME_IOTA_MS:str:'1000'}
            evidence:
              max_age_num_blocks: ${MAX_AGE_NUM_BLOCKS:str:'100000'}
              max_age_duration: ${MAX_AGE_DURATION:str:'172800000000000'}
              max_bytes: ${EVIDENCE_MAX_BYTES:str:'1048576'}
            validator:
              pub_key_types: ${PUB_KEY_TYPES:list:["ed25519"]}
            version: ${VERSION:dict:{}}
          voting_power: ${VOTING_POWER:str:'10'}
        init_fallback_gas: ${INIT_FALLBACK_GAS:int:0}
        keeper_allowed_retries: ${KEEPER_ALLOWED_RETRIES:int:3}
        keeper_timeout: ${KEEPER_TIMEOUT:float:30.0}
        max_attempts: ${MAX_ATTEMPTS:int:10}
        max_healthcheck: ${MAX_HEALTHCHECK:int:120}
        multisend_address: ${MULTISEND_ADDRESS:str:unknown111111111111111111111111111111111111}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TM_AFTER:int:200}
        retry_attempts: ${RETRY_ATTEMPTS:int:400}
        retry_timeout: ${RETRY_TIMEOUT:int:3}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
        request_retry_delay: ${REQUEST_RETRY_DELAY:float:1.0}
        request_timeout: ${REQUEST_TIMEOUT:float:10.0}
        round_timeout_seconds: ${ROUND_TIMEOUT:float:350.0}
        service_id: ${SERVICE_ID:str:solana_trader}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:unknown111111111111111111111111111111111111}
        agent_registry_address: ${AGENT_REGISTRY_ADDRESS:str:unknown111111111111111111111111111111111111}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: ${SLEEP_TIME:int:1}
        tendermint_check_sleep_delay: ${TM_CHECK_SLEEP_DELAY:int:3}
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: ${TM_MAX_RETRIES:int:5}
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        tx_timeout: ${TX_TIMEOUT:float:10.0}
        use_termination: ${USE_TERMINATION:bool:false}
        validate_timeout: ${VALIDATE_TIMEOUT:int:1205}
        history_check_timeout: ${HISTORY_CHECK_TIMEOUT:int:1205}
        token_symbol_whitelist: ${TOKEN_SYMBOL_WHITELIST:list:["coingecko_id=solana&address=So11111111111111111111111111111111111111112"]}
        strategies_kwargs: ${STRATEGIES_KWARGS:list:[["ma_period",20],["rsi_period",14],["rsi_overbought_threshold",70],["rsi_oversold_threshold",30]]}
        use_proxy_server: ${USE_PROXY_SERVER:bool:false}
        expected_swap_tx_cost: ${EXPECTED_SWAP_TX_COST:int:20000000}
        ipfs_fetch_retries: ${IPFS_FETCH_RETRIES:int:5}
        squad_vault: ${SQUAD_VAULT:str:39Zh4C687EXLY7CT8gjCxe2hUc3krESjUsqs7A1CKD5E}
        agent_balance_threshold: ${AGENT_BALANCE_THRESHOLD:int:50000000}
        multisig_balance_threshold: ${MULTISIG_BALANCE_THRESHOLD:int:1000000000}
        tracked_tokens: ${TRACKED_TOKENS:list:[]}
        refill_action_timeout: ${REFILL_ACTION_TIMEOUT:int:10}
        rpc_polling_interval: ${RPC_POLLING_INTERVAL:int:5}
        epsilon: ${EPSILON:float:0.1}
        sharpe_threshold: ${SHARPE_THRESHOLD:float:1.0}
    benchmark_tool: &id004
      args:
        log_dir: ${LOG_DIR:str:/benchmarks}
    get_balance: &id001
      args:
        url: ${SOLANA_RPC:str:replace_with_a_solana_rpc}
    token_accounts: *id001
    coingecko: &id005
      args:
        endpoint: ${COINGECKO_ENDPOINT:str:https://api.coingecko.com/api/v3/coins/{token_id}/market_chart?vs_currency=usd&days=1}
        api_key: ${COINGECKO_API_KEY:str:null}
        prices_field: ${COINGECKO_PRICES_FIELD:str:prices}
        requests_per_minute: ${COINGECKO_REQUESTS_PER_MINUTE:int:5}
        credits: ${COINGECKO_CREDITS:int:10000}
        rate_limited_code: ${COINGECKO_RATE_LIMITED_CODE:int:429}
    tx_settlement_proxy: &id006
      args:
        parameters:
          amount: ${TX_PROXY_AMOUNT:int:100000000}
          slippageBps: ${TX_PROXY_SLIPPAGE_BPS:int:1}
        response_key: ${TX_PROXY_RESPONSE_KEY:str:null}
        response_type: ${TX_PROXY_RESPONSE_TYPE:str:dict}
        retries: ${TX_PROXY_RETRIES:int:5}
        url: ${TX_PROXY_URL:str:http://localhost:3000/tx}
1:
  models:
    params:
      args:
        setup: *id002
        cleanup_history_depth: ${CLEANUP_HISTORY_DEPTH:int:1}
        cleanup_history_depth_current: ${CLEANUP_HISTORY_DEPTH_CURRENT:int:null}
        drand_public_key: ${DRAND_PUBLIC_KEY:str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
        finalize_timeout: ${FINALIZE_TIMEOUT:float:60.0}
        genesis_config: *id003
        init_fallback_gas: ${INIT_FALLBACK_GAS:int:0}
        keeper_allowed_retries: ${KEEPER_ALLOWED_RETRIES:int:3}
        keeper_timeout: ${KEEPER_TIMEOUT:float:30.0}
        max_attempts: ${MAX_ATTEMPTS:int:10}
        max_healthcheck: ${MAX_HEALTHCHECK:int:120}
        multisend_address: ${MULTISEND_ADDRESS:str:unknown111111111111111111111111111111111111}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TM_AFTER:int:200}
        retry_attempts: ${RETRY_ATTEMPTS:int:400}
        retry_timeout: ${RETRY_TIMEOUT:int:3}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
        request_retry_delay: ${REQUEST_RETRY_DELAY:float:1.0}
        request_timeout: ${REQUEST_TIMEOUT:float:10.0}
        round_timeout_seconds: ${ROUND_TIMEOUT:float:350.0}
        service_id: ${SERVICE_ID:str:solana_trader}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:unknown111111111111111111111111111111111111}
        agent_registry_address: ${AGENT_REGISTRY_ADDRESS:str:unknown111111111111111111111111111111111111}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: ${SLEEP_TIME:int:1}
        tendermint_check_sleep_delay: ${TM_CHECK_SLEEP_DELAY:int:3}
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: ${TM_MAX_RETRIES:int:5}
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        tx_timeout: ${TX_TIMEOUT:float:10.0}
        use_termination: ${USE_TERMINATION:bool:false}
        validate_timeout: ${VALIDATE_TIMEOUT:int:1205}
        history_check_timeout: ${HISTORY_CHECK_TIMEOUT:int:1205}
        token_symbol_whitelist: ${TOKEN_SYMBOL_WHITELIST:list:["coingecko_id=solana&address=So11111111111111111111111111111111111111112"]}
        strategies_kwargs: ${STRATEGIES_KWARGS:list:[["ma_period",20],["rsi_period",14],["rsi_overbought_threshold",70],["rsi_oversold_threshold",30]]}
        use_proxy_server: ${USE_PROXY_SERVER:bool:false}
        expected_swap_tx_cost: ${EXPECTED_SWAP_TX_COST:int:20000000}
        ipfs_fetch_retries: ${IPFS_FETCH_RETRIES:int:5}
        squad_vault: ${SQUAD_VAULT:str:39Zh4C687EXLY7CT8gjCxe2hUc3krESjUsqs7A1CKD5E}
        agent_balance_threshold: ${AGENT_BALANCE_THRESHOLD:int:50000000}
        multisig_balance_threshold: ${MULTISIG_BALANCE_THRESHOLD:int:1000000000}
        tracked_tokens: ${TRACKED_TOKENS:list:[]}
        refill_action_timeout: ${REFILL_ACTION_TIMEOUT:int:10}
        rpc_polling_interval: ${RPC_POLLING_INTERVAL:int:5}
        epsilon: ${EPSILON:float:0.1}
        sharpe_threshold: ${SHARPE_THRESHOLD:float:1.0}
    benchmark_tool: *id004
    get_balance: *id001
    token_accounts: *id001
    coingecko: *id005
    tx_settlement_proxy: *id006
2:
  models:
    params:
      args:
        setup: *id002
        cleanup_history_depth: ${CLEANUP_HISTORY_DEPTH:int:1}
        cleanup_history_depth_current: ${CLEANUP_HISTORY_DEPTH_CURRENT:int:null}
        drand_public_key: ${DRAND_PUBLIC_KEY:str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
        finalize_timeout: ${FINALIZE_TIMEOUT:float:60.0}
        genesis_config: *id003
        init_fallback_gas: ${INIT_FALLBACK_GAS:int:0}
        keeper_allowed_retries: ${KEEPER_ALLOWED_RETRIES:int:3}
        keeper_timeout: ${KEEPER_TIMEOUT:float:30.0}
        max_attempts: ${MAX_ATTEMPTS:int:10}
        max_healthcheck: ${MAX_HEALTHCHECK:int:120}
        multisend_address: ${MULTISEND_ADDRESS:str:unknown111111111111111111111111111111111111}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TM_AFTER:int:200}
        retry_attempts: ${RETRY_ATTEMPTS:int:400}
        retry_timeout: ${RETRY_TIMEOUT:int:3}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
        request_retry_delay: ${REQUEST_RETRY_DELAY:float:1.0}
        request_timeout: ${REQUEST_TIMEOUT:float:10.0}
        round_timeout_seconds: ${ROUND_TIMEOUT:float:350.0}
        service_id: ${SERVICE_ID:str:solana_trader}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:unknown111111111111111111111111111111111111}
        agent_registry_address: ${AGENT_REGISTRY_ADDRESS:str:unknown111111111111111111111111111111111111}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: ${SLEEP_TIME:int:1}
        tendermint_check_sleep_delay: ${TM_CHECK_SLEEP_DELAY:int:3}
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: ${TM_MAX_RETRIES:int:5}
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        tx_timeout: ${TX_TIMEOUT:float:10.0}
        use_termination: ${USE_TERMINATION:bool:false}
        validate_timeout: ${VALIDATE_TIMEOUT:int:1205}
        history_check_timeout: ${HISTORY_CHECK_TIMEOUT:int:1205}
        token_symbol_whitelist: ${TOKEN_SYMBOL_WHITELIST:list:["coingecko_id=solana&address=So11111111111111111111111111111111111111112"]}
        strategies_kwargs: ${STRATEGIES_KWARGS:list:[["ma_period",20],["rsi_period",14],["rsi_overbought_threshold",70],["rsi_oversold_threshold",30]]}
        use_proxy_server: ${USE_PROXY_SERVER:bool:false}
        expected_swap_tx_cost: ${EXPECTED_SWAP_TX_COST:int:20000000}
        ipfs_fetch_retries: ${IPFS_FETCH_RETRIES:int:5}
        squad_vault: ${SQUAD_VAULT:str:39Zh4C687EXLY7CT8gjCxe2hUc3krESjUsqs7A1CKD5E}
        agent_balance_threshold: ${AGENT_BALANCE_THRESHOLD:int:50000000}
        multisig_balance_threshold: ${MULTISIG_BALANCE_THRESHOLD:int:1000000000}
        tracked_tokens: ${TRACKED_TOKENS:list:[]}
        refill_action_timeout: ${REFILL_ACTION_TIMEOUT:int:10}
        rpc_polling_interval: ${RPC_POLLING_INTERVAL:int:5}
        epsilon: ${EPSILON:float:0.1}
        sharpe_threshold: ${SHARPE_THRESHOLD:float:1.0}
    benchmark_tool: *id004
    get_balance: *id001
    token_accounts: *id001
    coingecko: *id005
    tx_settlement_proxy: *id006
3:
  models:
    params:
      args:
        setup: *id002
        cleanup_history_depth: ${CLEANUP_HISTORY_DEPTH:int:1}
        cleanup_history_depth_current: ${CLEANUP_HISTORY_DEPTH_CURRENT:int:null}
        drand_public_key: ${DRAND_PUBLIC_KEY:str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
        finalize_timeout: ${FINALIZE_TIMEOUT:float:60.0}
        genesis_config: *id003
        init_fallback_gas: ${INIT_FALLBACK_GAS:int:0}
        keeper_allowed_retries: ${KEEPER_ALLOWED_RETRIES:int:3}
        keeper_timeout: ${KEEPER_TIMEOUT:float:30.0}
        max_attempts: ${MAX_ATTEMPTS:int:10}
        max_healthcheck: ${MAX_HEALTHCHECK:int:120}
        multisend_address: ${MULTISEND_ADDRESS:str:unknown111111111111111111111111111111111111}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TM_AFTER:int:200}
        retry_attempts: ${RETRY_ATTEMPTS:int:400}
        retry_timeout: ${RETRY_TIMEOUT:int:3}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:60}
        request_retry_delay: ${REQUEST_RETRY_DELAY:float:1.0}
        request_timeout: ${REQUEST_TIMEOUT:float:10.0}
        round_timeout_seconds: ${ROUND_TIMEOUT:float:350.0}
        service_id: ${SERVICE_ID:str:solana_trader}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:unknown111111111111111111111111111111111111}
        agent_registry_address: ${AGENT_REGISTRY_ADDRESS:str:unknown111111111111111111111111111111111111}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: ${SLEEP_TIME:int:1}
        tendermint_check_sleep_delay: ${TM_CHECK_SLEEP_DELAY:int:3}
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: ${TM_MAX_RETRIES:int:5}
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        tx_timeout: ${TX_TIMEOUT:float:10.0}
        use_termination: ${USE_TERMINATION:bool:false}
        validate_timeout: ${VALIDATE_TIMEOUT:int:1205}
        history_check_timeout: ${HISTORY_CHECK_TIMEOUT:int:1205}
        token_symbol_whitelist: ${TOKEN_SYMBOL_WHITELIST:list:["coingecko_id=solana&address=So11111111111111111111111111111111111111112"]}
        strategies_kwargs: ${STRATEGIES_KWARGS:list:[["ma_period",20],["rsi_period",14],["rsi_overbought_threshold",70],["rsi_oversold_threshold",30]]}
        use_proxy_server: ${USE_PROXY_SERVER:bool:false}
        expected_swap_tx_cost: ${EXPECTED_SWAP_TX_COST:int:20000000}
        ipfs_fetch_retries: ${IPFS_FETCH_RETRIES:int:5}
        squad_vault: ${SQUAD_VAULT:str:39Zh4C687EXLY7CT8gjCxe2hUc3krESjUsqs7A1CKD5E}
        agent_balance_threshold: ${AGENT_BALANCE_THRESHOLD:int:50000000}
        multisig_balance_threshold: ${MULTISIG_BALANCE_THRESHOLD:int:1000000000}
        tracked_tokens: ${TRACKED_TOKENS:list:[]}
        refill_action_timeout: ${REFILL_ACTION_TIMEOUT:int:10}
        rpc_polling_interval: ${RPC_POLLING_INTERVAL:int:5}
        epsilon: ${EPSILON:float:0.1}
        sharpe_threshold: ${SHARPE_THRESHOLD:float:1.0}
    benchmark_tool: *id004
    get_balance: *id001
    token_accounts: *id001
    coingecko: *id005
    tx_settlement_proxy: *id006
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${RPC_0:str:http://host.docker.internal:8545}
        chain_id: ${CHAIN_ID:int:1399811149}
        default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
        poa_chain: ${POA_CHAIN:bool:false}
1:
  config:
    ledger_apis:
      ethereum:
        address: ${RPC_1:str:http://host.docker.internal:8545}
        chain_id: ${CHAIN_ID:int:1399811149}
        default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
        poa_chain: ${POA_CHAIN:bool:false}
2:
  config:
    ledger_apis:
      ethereum:
        address: ${RPC_2:str:http://host.docker.internal:8545}
        chain_id: ${CHAIN_ID:int:1399811149}
        default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
        poa_chain: ${POA_CHAIN:bool:false}
3:
  config:
    ledger_apis:
      ethereum:
        address: ${RPC_3:str:http://host.docker.internal:8545}
        chain_id: ${CHAIN_ID:int:1399811149}
        default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
        poa_chain: ${POA_CHAIN:bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${ACN_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
is_abstract: false
