agent_name: solana_trader
author: valory
version: 0.1.0
license: Apache-2.0
description: Solana trader agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeibm2adzlongvgzyepiiymb3hxpsjb43qgr7j4uydebjzcpdrwm3om
  __init__.py: bafybeig4rclm2fca7pv35dtigdm3slje4o4urhybxdkkdy2gd5p6d5gfju
fingerprint_ignore_patterns: []
connections:
- eightballer/dcxt:0.1.0:bafybeicyeg2jnnvbhmles6gssw5zj2mjvcr2j2lyp5jrzdft3qsrnwgv5a
- valory/abci:0.1.0:bafybeie4eixvrdpc5ifoovj24a6res6g2e22dl6di6gzib7d3fczshzyti
- valory/http_client:0.23.0:bafybeihi772xgzpqeipp3fhmvpct4y6e6tpjp4sogwqrnf3wqspgeilg4u
- valory/ipfs:0.1.0:bafybeiefkqvh5ylbk77xylcmshyuafmiecopt4gvardnubq52psvogis6a
- valory/ledger:0.19.0:bafybeihynkdraqthjtv74qk3nc5r2xubniqx2hhzpxn7bd4qmlf7q4wruq
- valory/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
contracts:
- eightballer/erc_20:0.1.0:bafybeifjtxoyahzgrn622tipbrv2mx6r22fazawbffzszymjdlzs3uikbq
- valory/service_registry:0.1.0:bafybeieqgcuxmz4uxvlyb62mfsf33qy4xwa5lrij4vvcmrtcsfkng43oyq
- valory/multisend:0.1.0:bafybeig5byt5urg2d2bsecufxe5ql7f4mezg3mekfleeh32nmuusx66p4y
- valory/gnosis_safe:0.1.0:bafybeiho6sbfts3zk3mftrngw37d5qnlvkqtnttt3fzexmcwkeevhu4wwi
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeihi4cvrnf5ne7t5cxcwix3dbtfjucfjux6zn4wouebjx3ldmrmnpm
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- valory/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- valory/acn:1.1.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- valory/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
- valory/tendermint:0.1.0:bafybeig4mi3vmlv5zpbjbfuzcgida6j5f2nhrpedxicmrrfjweqc5r7cra
skills:
- valory/abstract_abci:0.1.0:bafybeihu2bcgjk2tqjiq2zhk3uogtfszqn4osvdt7ho3fubdpdj4jgdfjm
- valory/abstract_round_abci:0.1.0:bafybeibovsktd3uxur45nrcomq5shcn46cgxd5idmhxbmjhg32c5abyqim
- valory/registration_abci:0.1.0:bafybeicnth5q4httefsusywx3zrrq4al47owvge72dqf2fziruicq6hqta
- valory/reset_pause_abci:0.1.0:bafybeievjciqdvxhqxfjd4whqs27h6qbxqzrae7wwj7fpvxlvmtw3x35im
- valory/market_data_fetcher_abci:0.1.0:bafybeidmyipsuadj3aoxfto4iarkqoyk4q46qjg2fwdkorqgoezb4hvrcq
- valory/strategy_evaluator_abci:0.1.0:bafybeiaxgnxhkh36rmu4u7zsyjp3zow7if6aabkicwcxwhaofp24i7dcji
- valory/trader_abci:0.1.0:bafybeig5nkiu7vbky27hv64s3imyyufxsz5ljg4mx5f4mbouq7x2hcp45e
- valory/transaction_settlement_abci:0.1.0:bafybeihq2yenstblmaadzcjousowj5kfn5l7ns5pxweq2gcrsczfyq5wzm
- valory/trader_decision_maker_abci:0.1.0:bafybeih7duxvbjevmeez4bvdpahgvefoik3hnpjq3ik5g4jaqbuw5rybtu
- valory/ipfs_package_downloader:0.1.0:bafybeid54srronvfqbvcdjgtuhmr4mbndjkpxtgzguykeg4p3wwj3zboyi
- valory/portfolio_tracker_abci:0.1.0:bafybeihnpy4fso2q6f5osf3u2yg5wkgrfuk6wewimhhwfglfktrrvliaju
default_ledger: ethereum
required_ledgers:
- ethereum
- solana
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.55.0
  open-aea-ledger-solana:
    version: ==1.55.0
  open-aea-ledger-ethereum:
    version: ==1.55.0
  open-aea-test-autonomy:
    version: ==0.15.2
  pyalgotrade:
    version: ==0.20
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/trader_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ipfs_package_downloader:0.1.0
type: skill
models:
  params:
    args:
      cleanup_freq: ${int:50}
      timeout_limit: ${int:3}
      file_hash_to_id: ${list:[["bafybeic2fpf5ozhkf5jgzmppmfsprqw5ayfx6spgl3owuws464n7mkhpqi",["sma_strategy"]]]}
      component_yaml_filename: ${str:component.yaml}
      entry_point_key: ${str:entry_point}
      callable_keys: ${list:["run_callable","transform_callable","evaluate_callable"]}
---
public_id: valory/trader_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  get_balance:
    args:
      api_id: ${str:get_balance}
      headers:
        Content-Type: ${str:application/json}
      method: ${str:POST}
      parameters: ${dict:{}}
      response_key: ${str:result:value}
      response_type: ${str:int}
      error_key: ${str:error:message}
      error_type: ${str:str}
      retries: ${int:5}
      url: ${str:https://api.mainnet-beta.solana.com}
  token_accounts:
    args:
      api_id: ${str:token_accounts}
      headers:
        Content-Type: ${str:application/json}
      method: ${str:POST}
      parameters: ${dict:{}}
      response_key: ${str:result:value}
      response_type: ${str:list}
      error_key: ${str:error:message}
      error_type: ${str:str}
      retries: ${int:5}
      url: ${str:https://api.mainnet-beta.solana.com}
  coingecko:
    args:
      endpoint: ${str:https://api.coingecko.com/api/v3/coins/{token_id}/market_chart?vs_currency=usd&days=1}
      api_key: ${str:null}
      prices_field: ${str:prices}
      requests_per_minute: ${int:5}
      credits: ${int:10000}
      rate_limited_code: ${int:429}
  tx_settlement_proxy:
    args:
      api_id: ${str:tx_settlement_proxy}
      headers:
        Content-Type: ${str:application/json}
      method: ${str:POST}
      parameters:
        amount: ${int:100000000}
        slippageBps: ${int:5}
        resendAmount: ${int:200}
        timeoutInMs: ${int:120000}
        priorityFee: ${int:5000000}
      response_key: ${str:null}
      response_type: ${str:dict}
      retries: ${int:5}
      url: ${str:http://localhost:3000/tx}
  params:
    args:
      setup:
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold: ${int:null}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
      cleanup_history_depth: ${int:1}
      cleanup_history_depth_current: ${int:null}
      finalize_timeout: ${float:60.0}
      genesis_config:
        genesis_time: ${str:2022-09-26T00:00:00.000000000Z}
        chain_id: ${str:chain-c4daS1}
        consensus_params:
          block:
            max_bytes: ${str:22020096}
            max_gas: ${str:-1}
            time_iota_ms: ${str:1000}
          evidence:
            max_age_num_blocks: ${str:100000}
            max_age_duration: ${str:172800000000000}
            max_bytes: ${str:1048576}
          validator:
            pub_key_types: ${list:["ed25519"]}
          version: ${dict:{}}
        voting_power: ${str:10}
      init_fallback_gas: ${int:0}
      keeper_allowed_retries: ${int:3}
      keeper_timeout: ${float:30.0}
      max_attempts: ${int:10}
      reset_tendermint_after: ${int:2}
      retry_attempts: ${int:400}
      retry_timeout: ${int:3}
      request_retry_delay: ${float:1.0}
      request_timeout: ${float:10.0}
      service_id: ${str:solana_trader}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_check_sleep_delay: ${int:3}
      tendermint_max_retries: ${int:5}
      tx_timeout: ${float:10.0}
      round_timeout_seconds: ${float:350.0}
      proxy_round_timeout_seconds: ${float:1200.0}
      validate_timeout: ${int:1205}
      history_check_timeout: ${int:1205}
      reset_pause_duration: ${int:30}
      max_healthcheck: ${int:43200}
      multisend_address: ${str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      drand_public_key: ${str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
      service_registry_address: ${str:null}
      agent_registry_address: ${str:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: ${int:10}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      use_termination: ${bool:false}
      on_chain_service_id: ${int:null}
      token_symbol_whitelist: ${list:["coingecko_id=weth&address=7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs"]}
      tracked_tokens: ${list:["7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs"]}
      strategies_kwargs: ${list:[["ma_period",35]]}
      use_proxy_server: ${bool:false}
      expected_swap_tx_cost: ${int:20000000}
      ipfs_fetch_retries: ${int:5}
      squad_vault: ${str:GFWUcLp1equf4QtrRMj5RZasm8yshs4MZa2pR5Ghz54u}
      agent_balance_threshold: ${int:0}
      multisig_balance_threshold: ${int:0}
      refill_action_timeout: ${int:10}
      rpc_polling_interval: ${int:5}
      epsilon: ${float:0.1}
      sharpe_threshold: ${float:-10.1}
      ledger_ids: ${list:["ethereum"]}
      exchange_ids:
        ethereum:
        - balancer
      trade_size_in_base_token: ${float:0.0001}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:https://rpc.ankr.com/eth}
      chain_id: ${int:1}
      default_gas_price_strategy: ${str:eip1559}
      poa_chain: ${bool:false}
---
public_id: valory/http_client:0.23.0
type: connection
config:
  host: ${str:127.0.0.1}
  port: ${int:8000}
  timeout: ${int:1200}
---
public_id: eightballer/dcxt:0.1.0
type: connection
config:
  target_skill_id: valory/trader_abci:0.1.0
  exchanges:
  - name: ${str:balancer}
    key_path: ${str:ethereum_private_key.txt}
    kwargs:
      chain_id: ${str:mainnet}
      rpc_url: ${str:https://rpc.ankr.com/eth}
      etherscan_api_key: ${str:YOUR_ETHERSCAN_API_KEY}
