agent_name: solana_trader
author: valory
version: 0.1.0
license: Apache-2.0
description: Solana trader agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeig5bnpyiwsvqdaqubiw342kn3ncbd22i4vstlk3t5vcbtbdcfcad4
  __init__.py: bafybeig4rclm2fca7pv35dtigdm3slje4o4urhybxdkkdy2gd5p6d5gfju
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeihitte2x3mmbsuzsaijcdcdtywqvjflw37wx7a5urjcy2n73uzqlq
- valory/http_client:0.23.0:bafybeih5vzo22p2umhqo52nzluaanxx7kejvvpcpdsrdymckkyvmsim6gm
- valory/ipfs:0.1.0:bafybeifkrynw6jjg7bs7nw535m5bcrav5qab27vr5ktgfuvf65dpazc4ci
- valory/ledger:0.19.0:bafybeic3ft7l7ca3qgnderm4xupsfmyoihgi27ukotnz7b5hdczla2enya
- valory/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
contracts:
- valory/service_registry:0.1.0:bafybeihnvoscfmgmdl44vcoyqtraqdgmy3xqprqkgtuwfav3zdvek3eije
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- valory/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- valory/acn:1.1.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- valory/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
- valory/tendermint:0.1.0:bafybeig4mi3vmlv5zpbjbfuzcgida6j5f2nhrpedxicmrrfjweqc5r7cra
skills:
- valory/abstract_abci:0.1.0:bafybeiczqe4mvpr35owogzvyvh5nzd7qhx642i5vkxxzfzr5j3pmvr6kqe
- valory/abstract_round_abci:0.1.0:bafybeid47s4ojmbxscc2oxfkwt4hkpdgv5qivo5x5dfe2uxqv6ybvprxlm
- valory/registration_abci:0.1.0:bafybeiet4l2ayrzwqj6gphgpw4pgzkx653eli3lec7rl2a2rmzf6gegjcy
- valory/reset_pause_abci:0.1.0:bafybeigs6acxu65c7psilzlh6estqcc23w4eyjsh7eo2y55uwnwrpb4keu
- valory/market_data_fetcher_abci:0.1.0:bafybeiee2uhhay4mflvt5n2g75sv43bvciiemwxd5ago4rosp3pdqvjotm
- valory/solana_strategy_evaluator_abci:0.1.0:bafybeigqaurzdrxi3skwbhaz5qstuckrj2fhw6dm4jgeckgskogcvrwnyi
- valory/solana_trader_abci:0.1.0:bafybeia6o5lzi5uxgwvzpkvtaar6p3jrp776pqqgfjs34ivfskpgtpkfii
- valory/solana_trader_decision_maker_abci:0.1.0:bafybeievzcxuyu7b76yimesjd4ytsmduf5xbb2r6fs3hnyimsuraicwmsa
- valory/ipfs_package_downloader:0.1.0:bafybeihiwmqdde44f5irlosfgcmtzbz3esootx3ypvwvrkpywsjoyhl4h4
default_ledger: ethereum
required_ledgers:
- ethereum
- solana
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.43.0.post2
  open-aea-ledger-ethereum:
    version: ==1.43.0.post2
  open-aea-test-autonomy:
    version: ==0.13.9.post1
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/solana_trader_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/solana_trader_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  params:
    args:
      setup:
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold: ${int:null}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
      cleanup_history_depth: ${int:1}
      cleanup_history_depth_current: ${int:null}
      finalize_timeout: ${float:60.0}
      genesis_config:
        genesis_time: ${str:2022-09-26T00:00:00.000000000Z}
        chain_id: ${str:chain-c4daS1}
        consensus_params:
          block:
            max_bytes: ${str:22020096}
            max_gas: ${str:-1}
            time_iota_ms: ${str:1000}
          evidence:
            max_age_num_blocks: ${str:100000}
            max_age_duration: ${str:172800000000000}
            max_bytes: ${str:1048576}
          validator:
            pub_key_types: ${list:["ed25519"]}
          version: ${dict:{}}
        voting_power: ${str:10}
      init_fallback_gas: ${int:0}
      keeper_allowed_retries: ${int:3}
      keeper_timeout: ${float:30.0}
      max_attempts: ${int:10}
      reset_tendermint_after: ${int:2}
      retry_attempts: ${int:400}
      retry_timeout: ${int:3}
      request_retry_delay: ${float:1.0}
      request_timeout: ${float:10.0}
      service_id: ${str:solana_trader}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_check_sleep_delay: ${int:3}
      tendermint_max_retries: ${int:5}
      tx_timeout: ${float:10.0}
      round_timeout_seconds: ${float:350.0}
      validate_timeout: ${int:1205}
      history_check_timeout: ${int:1205}
      reset_pause_duration: ${int:30}
      max_healthcheck: ${int:43200}
      multisend_address: ${str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      drand_public_key: ${str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
      service_registry_address: ${str:null}
      agent_registry_address: ${str:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: ${int:10}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      use_termination: ${bool:false}
      on_chain_service_id: ${int:null}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      selected_strategy: follow_trend_strategy
      token_symbol_whitelist: []
      coingecko_api_key: ''
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://host.docker.internal:8545}
      chain_id: ${int:1337}
      default_gas_price_strategy: ${str:eip1559}
      poa_chain: ${bool:false}
